AY2425S1-CS2103T-F13-3/tp

docs/AboutUs.md
docs/team/casperngeen.md

Update About Us

---

docs/AboutUs.md
docs/team/yizhong187.md

Edit Yizhong's info in AboutUs.md and create portfolio page for Yizhong.

Edit Yizhong's About Us

---

docs/UserGuide.md

Update UserGuide.md with 'view' command

---

docs/UserGuide.md

Update UserGuide.md with 'create' command, which replaces the 'add' command originally.
Updated 'delete' command with new format as well.

Update UserGuide.md commands

---

docs/DeveloperGuide.md
docs/UserGuide.md

Remove AB3 occurences and fix minor errors

---

docs/leslieyip02.md
docs/team/casperngeen.md
docs/team/fyl2003.md
docs/team/leslieyip02.md
docs/team/yizhong187.md

Fix AboutUs duplication

---

docs/DeveloperGuide.md

Update developer guide product scope

---

docs/AboutUs.md

Remove duplicates in AboutUs.md file

---

docs/AboutUs.md

Change the hyperlink under Leslie and Yilong to a valid one
Closes #60

Change hyperlink under portfolio

---

src/main/java/seedu/address/model/person/Client.java
src/main/java/seedu/address/model/person/Contact.java
src/main/java/seedu/address/model/person/Date.java
src/main/java/seedu/address/model/person/Service.java
src/main/java/seedu/address/model/person/Vendor.java

Create new classes that extends Contact class

---

src/main/java/seedu/address/model/person/Service.java
src/main/java/seedu/address/model/person/UniqueContactList.java
src/main/java/seedu/address/model/person/Vendor.java
src/main/java/seedu/address/model/person/exceptions/ContactNotFoundException.java
src/main/java/seedu/address/model/person/exceptions/DuplicateContactException.java

Part of #64. This PR implements `UniqueContactList`, which is adapted form `UniquePersonList`. This is necessary since the `AddressBook` class uses `UniquePersonList` to keep track of `Person` objects.

Add UniqueContactList

---

src/main/java/seedu/ddd/model/contact/client/Date.java
src/test/java/seedu/ddd/testutil/ClientUtil.java

Change the date representation from string to
LocalDate and allows multiple date format.

Change representation of Date

---

src/main/java/seedu/ddd/model/contact/client/Client.java
src/main/java/seedu/ddd/model/contact/vendor/Vendor.java

Fix `ContactTest::toStringMethod` test fail introduced by #93.

Fix toString fail

---

src/main/java/seedu/ddd/model/contact/client/Date.java
src/test/java/seedu/ddd/model/contact/client/DateTest.java
src/test/java/seedu/ddd/model/contact/common/AddressTest.java
src/test/java/seedu/ddd/model/contact/common/ContactTest.java
src/test/java/seedu/ddd/model/contact/common/EmailTest.java
src/test/java/seedu/ddd/model/contact/common/IdTest.java
src/test/java/seedu/ddd/model/contact/common/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/ddd/model/contact/common/NameTest.java
src/test/java/seedu/ddd/model/contact/common/PhoneTest.java
src/test/java/seedu/ddd/model/contact/common/UniqueContactListTest.java
src/test/java/seedu/ddd/model/contact/vendor/ServiceTest.java

Branch yilong add test cases related to date

---

src/main/java/seedu/ddd/logic/parser/AddCommandParser.java
src/main/java/seedu/ddd/logic/parser/AddressBookParser.java
src/test/java/seedu/ddd/logic/parser/AddCommandParserTest.java

Rename AddContactCommandParser into AddCommandParser

---

src/main/java/seedu/ddd/logic/Messages.java
src/main/java/seedu/ddd/logic/commands/ListCommand.java
src/main/java/seedu/ddd/model/contact/common/ContactPredicateBuilder.java
src/test/java/seedu/ddd/logic/LogicManagerTest.java
src/test/java/seedu/ddd/logic/commands/ListCommandTest.java
src/test/java/seedu/ddd/logic/parser/ListCommandParserTest.java

Added List Command Test Cases

---

build.gradle

Change `addressbook.jar` to `ddd.jar` for release.

Update JAR build name

---

docs/diagrams/ModelClassDiagram.puml

I just add a few lines to show the new event class.

Add UML diagram for Event

---

src/main/java/seedu/ddd/model/Model.java
src/main/java/seedu/ddd/model/ModelManager.java
src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
src/main/java/seedu/ddd/model/event/common/predicate/DescriptionContainsKeywordsPredicate.java
src/main/java/seedu/ddd/model/event/common/predicate/EventIdPredicate.java
src/main/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilder.java
src/test/java/seedu/ddd/logic/commands/AddCommandTest.java
src/test/java/seedu/ddd/logic/commands/ListEventCommandTest.java
src/test/java/seedu/ddd/logic/parser/ListCommandParserTest.java
src/test/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilderTest.java
src/test/java/seedu/ddd/model/contact/common/predicate/VendorTypePredicateTest.java
src/test/java/seedu/ddd/model/event/common/predicate/DescriptionContainsKeywordsPredicateTest.java
src/test/java/seedu/ddd/model/event/common/predicate/EventIdPredicateTest.java
src/test/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilderTest.java

Add test cases for `list` command

---

src/test/java/seedu/ddd/logic/commands/AddEventCommandTest.java

Fix whitespace introduced by #135.

Fix whitespace

---

docs/diagrams/ModelClassDiagram.puml

Update UML Diagram for ModelClassDiagram

---

src/main/java/seedu/ddd/logic/commands/ListCommand.java
src/main/java/seedu/ddd/model/ModelManager.java

Fix `Model::displayedList` not updating correctly.

Fix displayed list desync

---

docs/diagrams/BetterModelClassDiagram.puml

Replace Person with Contact in UML

---

src/main/java/seedu/ddd/model/util/SampleDataUtil.java

Error caused by `SampleDataUtil::getSampleAddressBook`.

Fix compile error

---

src/main/java/seedu/ddd/logic/commands/ListClientCommand.java
src/main/java/seedu/ddd/logic/commands/ListContactCommand.java
src/main/java/seedu/ddd/logic/commands/ListEventCommand.java
src/main/java/seedu/ddd/logic/commands/ListVendorCommand.java
src/main/java/seedu/ddd/logic/parser/ListClientCommandParser.java
src/main/java/seedu/ddd/logic/parser/ListVendorCommandParser.java
src/main/java/seedu/ddd/model/ModelManager.java
src/main/java/seedu/ddd/model/contact/common/predicate/ClientPredicateBuilder.java
src/main/java/seedu/ddd/model/contact/common/predicate/ClientTypePredicate.java
src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
src/main/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilder.java
src/main/java/seedu/ddd/model/contact/common/predicate/VendorTypePredicate.java
src/test/java/seedu/ddd/logic/commands/ListClientCommandTest.java
src/test/java/seedu/ddd/logic/commands/ListEventCommandTest.java
src/test/java/seedu/ddd/logic/commands/ListVendorCommandTest.java
src/test/java/seedu/ddd/model/ModelManagerTest.java
src/test/java/seedu/ddd/model/contact/common/predicate/ClientPredicateBuilderTest.java
src/test/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilderTest.java
src/test/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilderTest.java

Closes #163.
The bug was caused by 2 things: 
- `ContactPredicateBuilder` needs the `FLAG_CLIENT` and `FLAG_VENDOR` flags but it wasn't supplied.
- `displayedList` listener is not triggered if the predicate doesn't change.
I've created the `ClientPredicateBuilder` and `VendorPredicateBuilder` to extend `ContactPredicateBuilder`.

Fix listing

---

src/main/resources/view/HelpWindow.css
src/main/resources/view/MainWindow.css
src/main/resources/view/Sidebar.css

Closes #143. This just changes the background and text color to match the rest of the app.

Update HelpWindow styles

---

src/main/java/seedu/ddd/model/contact/common/Phone.java
src/test/java/seedu/ddd/model/contact/common/PhoneTest.java

Added max length of 20 as phone number constraint. 
Closes #203

Add max length of 20 for phone number

---

src/main/resources/view/EventCard.fxml

Prevent client and vendor fields from collapsing

---

src/main/java/seedu/ddd/logic/Messages.java
src/main/java/seedu/ddd/logic/commands/DeleteCommand.java
src/main/java/seedu/ddd/model/AddressBook.java
src/test/java/seedu/ddd/logic/commands/DeleteCommandTest.java

Simple fix on possible list of empty vendors

---

docs/UserGuide.md
src/main/java/seedu/ddd/storage/JsonSerializableAddressBook.java

add filter for checking possible null values

Add check for event related problem

---

docs/DeveloperGuide.md

Remove whitespace in DG to silence whitespace warnings.

Remove whitespace in DG

---

docs/UserGuide.md

Unlike markdown tables, HTML tables do not have styles.

Fix HTML table styles

---

docs/diagrams/ModelClassDiagram.puml

Update UML diagrams for model

---

src/main/java/seedu/ddd/logic/commands/EditContactCommand.java
src/main/java/seedu/ddd/model/contact/common/Email.java
src/main/java/seedu/ddd/model/contact/common/UniqueContactList.java
src/test/java/seedu/ddd/logic/commands/EditContactCommandTest.java
src/test/java/seedu/ddd/logic/parser/AddressBookParserTest.java

Closes 242.
Updated `EditCommand` to check if the edit will create duplicated commands.

Fix EditCommand

---

docs/diagrams/ModelClassDiagram.puml
docs/diagrams/StorageClassDiagram.puml

- Updated labels for Model UML diagram
- Updated classes for Storage UML diagram
Storage:
Model:

Update UML diagrams

---

docs/DeveloperGuide.md
docs/UserGuide.md

Fix #243, Fixes #282, Fixes #284, Fixes #268 
Also fixes #270

Update User Stories and fix typos in UG.

---

docs/UserGuide.md
src/test/java/seedu/ddd/model/contact/common/AddressTest.java

Updated example commands to include add event

---

docs/DeveloperGuide.md
docs/diagrams/ModelClassDiagram.puml

Closes #288
Closes #287
Closes #278

Update manual test cases in DG

---

docs/UserGuide.md
docs/_markbind/layouts/default.md

Reverted HTML tables back to markdown tables

---

src/main/java/seedu/ddd/model/common/Name.java
src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
src/main/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilder.java
src/main/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilder.java
src/test/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilderTest.java
src/test/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilderTest.java

Fixed bug for email and phone where input is invalid

---

docs/DeveloperGuide.md
docs/UserGuide.md

Update User Guide to include hyperlinks and more tips

---

docs/UserGuide.md
src/main/java/seedu/ddd/logic/parser/ParserUtil.java

Fixes #261 and Updated UG for `list` command for typo.

Fix error message for id and update ug

---

docs/UserGuide.md

Add known issues

---

src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java
src/main/java/seedu/ddd/model/contact/common/predicate/VendorPredicateBuilder.java
src/main/java/seedu/ddd/model/event/common/predicate/EventPredicateBuilder.java

Improve the code quality by applying more SLAP

Change the check to use previously used method

---

src/main/java/seedu/ddd/model/contact/common/predicate/ContactPredicateBuilder.java

Fix typo with import statements
